### ISSUE TITLE
Improving the Navigation Bar for a Better User Experience

### ISSUE THREAD

**Issue by premsaivarmachekuri** [kamallochan2004/QR-codeGenerator#5]
Closes #6 

## Description

The project's current navigation bar lacks certain enhancements, resulting in a less-than-optimal user experience. In this proposal, I suggest making several feature enhancements to the navigation bar, which will greatly benefit the project and its users.

#### GitHub Button

- **Description:** Provide easy access to the GitHub repository.
- **Use:** Simplifies navigation and encourages collaboration.

#### Contributors Section

- **Description:** Display contributors and their GitHub profiles.
- **Use:** Recognizes and motivates contributors.

#### UI Enhancement

- **Description:** Improve visual appeal and user-friendliness.
- **Use:** Ensures a smooth and efficient user experience.

## Screenshots
![image](https://github.com/kamallochan2004/QR-codeGenerator/assets/110842297/7e54856e-8dab-41ea-8c81-fd6c1b77b829)

## Additional Context

I have an experience in enhancing UI elements and bringing value to open-source projects. These proposed changes will enhance the QR-Code Generator project's usability and community engagement.

- [x] Read [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines)

**Comment by kamallochan2004** [comment]
@premsaivarmachekuri Assigned!

**Comment by kamallochan2004** [comment]
Your PR is merged
